### ISSUE TITLE
Can we cut down the dependencies?

### ISSUE THREAD

**Issue by djowett** [4teamwork/ftw.mobilenavigation#39]
Hi I'm wanting to use this (for the second time),

once thing I notice is how many (fast moving) dependencies it pulls in, through ftw.upgrade.  This commonly gives me buildout errors due to pinned versions.  Such as the below:

Installing zopepy.
The constraint, 1.8.0, is not consistent with the requirement, 'six>=1.9.0'.
While:
  Installing zopepy.
Error: Bad constraint 1.8.0 six>=1.9.0

I can work my way through this, but it does leave me wondering if there is any way to reduce the amount of dependencies pulled in?  This product only uses a fraction of ftw.upgrade's functionality right?

**Comment by djowett** [comment]
btw solution to buildout error in this case was to pin 

    # Any higher in blessed pins six too high
    blessed = 1.9.4

**Comment by jone** [comment]
Oh, thanks for reporting.
I wasn't aware that we still have this problem. We've made a workaround in our company buildouts by pinning it as you did but then forgot to fix the problem.

I've made an issue at https://github.com/4teamwork/ftw.upgrade/issues/87 , but I'm not sure how fast I will have fixed it.

**Comment by jone** [comment]
So for answering the original question:
I think we should make it easier to have ftw.upgrade as a dependency instead of just not using it. This might mean some refactoring / changes there though.

**Comment by djowett** [comment]
Yep, I appreciate it's not my place to assign work on your product, but having blessed & pypath etc in my buildout when all I wanted was ftw.mobilenavigation is undesirable.

Maybe having a ftw.upgradesteps, or perhaps you can 
do something like 

     ftw.upgrade[stepsonly] 

though I suspect not.

It's more likely you could do 

     ftw.upgrade[all]

for products that really want the whizzy upgrade pages etc, whereas ftw.upgrade is enough for ftw.mobilenavigation and friends.  But I don't know how much effort & pain that might be.  A pipe dream maybe?

**Comment by jone** [comment]
Yes, something like that is probably best. I'm not sure why I didn't do that in the first place. :confused: 

Why is `path.py` a problem, by the way?

**Comment by djowett** [comment]
nothings a problem on it's own - it's just all together there's a lot of dependencies that I have to think "should I pin that, or should I let it update?" for.  Once I have to think that, then I start to think "what do I need this for anyway? this (e.g. blessed) is *really* different to my problem space!"....

**Comment by lukasgraf** [comment]
I think @djowett has a point here: The requirements for a package that just depends on `ftw.upgrade` because it needs to **define** upgrade steps (i.e. some ZCML directives and the `UpgradeStep` class) are really different from the use case where `ftw.upgrade` is used to **execute** the upgrades.

With the **upgrade directory** functionality, there's some overlap: After a quick glance I'd say we need `path.py` and `inflection`, and currently also `blessed` for some of the commands like `touch` and `create`. But `blessed` or whatever terminal library we'll might switch to could be made an extra - it's already [being used conditionally anyway](https://github.com/4teamwork/ftw.upgrade/blob/6257f9b11ed278d60606c4f786c3aa868ffcc67e/ftw/upgrade/command/terminal.py#L21-L27).

I think overall we would benefit from making an effort to keep it as simple as possible for packages to just use `ftw.upgrade` to define upgrade steps. For running them, you'd then just include `ftw.upgrade[fancypants]` from your buildout :wink:

**Comment by djowett** [comment]
@lukasgraf perfectly put!

Thanks!

**Comment by jone** [comment]
I made a pull-request to `ftw.upgrade`, making the `blessed` dependency optional: https://github.com/4teamwork/ftw.upgrade/pull/89
I wasn't aware that this could be done that easily :stuck_out_tongue_winking_eye: 

Droping other dependencies is more work though, and I don't think that we have other annoying or invasive dependencies, so I tend to just drop `blessend` and keep the rest as it is.

@djowett do you see problems with dependencies other than `blessed`?

**Comment by jone** [comment]
@djowett We've just released `ftw.upgrade = 1.15.0`, which has no dependency to `blessed` anymore. This should solve the dependency problems.
Please report if you have further trouble with our packages! :grinning:

**Comment by djowett** [comment]
@jone thanks for the quick work, I'm grateful for any improvement on that point.  @lukasgraf described the categories of use very well, but I should probably just learn to use the fancypants parts & benefit from them!  I think path.py (mentioned earlier) caught my eye because it had so many releases recently (8 in August).

Cheers!
